// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-wKOf0spXWLV-J0QC4l3tHnSvBU6CYk',
    appId: '1:462052883854:web:68422dfaabe5943d0538df',
    messagingSenderId: '462052883854',
    projectId: 'tbj-store-ptoject',
    authDomain: 'tbj-store-ptoject.firebaseapp.com',
    storageBucket: 'tbj-store-ptoject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf_mbVk-alUsaM2VUq26M1K_yua7lOYRs',
    appId: '1:462052883854:android:69e739a6bd40efd10538df',
    messagingSenderId: '462052883854',
    projectId: 'tbj-store-ptoject',
    storageBucket: 'tbj-store-ptoject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZTSo0m3rufvAWo7Xu1z7nYCBRZC_LY18',
    appId: '1:462052883854:ios:4c53f1927b067e8a0538df',
    messagingSenderId: '462052883854',
    projectId: 'tbj-store-ptoject',
    storageBucket: 'tbj-store-ptoject.appspot.com',
    iosClientId: '462052883854-0mtngnr7rmb30k12lp4ntbr6squulhrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.cupertinoStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZTSo0m3rufvAWo7Xu1z7nYCBRZC_LY18',
    appId: '1:462052883854:ios:4c53f1927b067e8a0538df',
    messagingSenderId: '462052883854',
    projectId: 'tbj-store-ptoject',
    storageBucket: 'tbj-store-ptoject.appspot.com',
    iosClientId: '462052883854-0mtngnr7rmb30k12lp4ntbr6squulhrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.cupertinoStore',
  );
}
